vich_uploader:
    db_driver: orm

    mappings:
        logo_images:
            uri_prefix: '%logo_images%'
            upload_destination: '%kernel.project_dir%/public%logo_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        images:
            uri_prefix: '%images%'
            upload_destination: '%kernel.project_dir%/public%images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
