version: '3.7'
volumes:
    dbdata:

services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'
        volumes:
            - dbdata:/var/lib/mysql

    mailer:
        image: schickling/mailcatcher
        ports:
            - '1025'
            - '1080'
